import type {
  LocalEnvironmentAction,
  LocalEnvironmentLifecycle,
  LocalEnvironmentPlatform,
} from "protocol";
import {
  LOCAL_ENVIRONMENT_SOURCE_TREE_PATH_ENV_VAR,
  LOCAL_ENVIRONMENT_WORKTREE_PATH_ENV_VAR,
} from "protocol";

export type LocalEnvironmentActionDraft = Omit<
  LocalEnvironmentAction,
  "platform"
> & {
  id: string;
  platform: LocalEnvironmentPlatform | null;
};

export type LocalEnvironmentLifecyclePlatformScripts = Partial<
  Record<LocalEnvironmentPlatform, string>
>;
export const LIFECYCLE_PLATFORM_ORDER: Array<LocalEnvironmentPlatform> = [
  "darwin",
  "linux",
  "win32",
];

export const SETUP_SCRIPT_PLACEHOLDER = `# Setup runs in the new worktree.
# Injected env vars:
# - ${LOCAL_ENVIRONMENT_SOURCE_TREE_PATH_ENV_VAR}: source tree path
# - ${LOCAL_ENVIRONMENT_WORKTREE_PATH_ENV_VAR}: new worktree path
#
# e.g.
cd "$${LOCAL_ENVIRONMENT_WORKTREE_PATH_ENV_VAR}"
pip install -r requirements.txt
npm install
./run/setup.sh`;

export const ACTION_SCRIPT_PLACEHOLDER = `# e.g.
npm install
npm run dev`;

export const CLEANUP_SCRIPT_PLACEHOLDER = `# e.g.
docker compose down --remove-orphans
rm -rf .cache/tmp`;

export function createDefaultAction(name: string): LocalEnvironmentActionDraft {
  return {
    id: createActionId(),
    name,
    icon: "tool",
    command: "",
    platform: null,
  };
}

export function getInitialActionDrafts(
  actions: Array<LocalEnvironmentAction>,
): Array<LocalEnvironmentActionDraft> {
  if (actions.length > 0) {
    return actions.map((action): LocalEnvironmentActionDraft => {
      return {
        ...action,
        id: createActionId(),
        platform: action.platform ?? null,
      };
    });
  }
  return [];
}

export function getLifecyclePlatformScripts(
  lifecycle: LocalEnvironmentLifecycle | null | undefined,
): LocalEnvironmentLifecyclePlatformScripts {
  return {
    darwin: lifecycle?.darwin?.script ?? "",
    linux: lifecycle?.linux?.script ?? "",
    win32: lifecycle?.win32?.script ?? "",
  };
}

export function buildEnvironmentToml({
  version,
  name,
  setupScript,
  setupPlatformScripts,
  cleanupScript,
  cleanupPlatformScripts,
  actions,
}: {
  version: number;
  name: string;
  setupScript: string;
  setupPlatformScripts: LocalEnvironmentLifecyclePlatformScripts;
  cleanupScript: string;
  cleanupPlatformScripts: LocalEnvironmentLifecyclePlatformScripts;
  actions: Array<LocalEnvironmentActionDraft>;
}): string {
  const persistedActions = getPersistedActions(actions);
  const lines = new Array<string>();
  const trimmedCleanupScript = cleanupScript.trim();
  lines.push("# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY");
  lines.push(`version = ${version}`);
  lines.push(`name = ${formatTomlString(name)}`);
  appendLifecycleSection(lines, "setup", setupScript, setupPlatformScripts);
  appendLifecycleSection(
    lines,
    "cleanup",
    trimmedCleanupScript,
    cleanupPlatformScripts,
  );

  if (persistedActions.length > 0) {
    lines.push("");
  }

  for (const action of persistedActions) {
    lines.push("[[actions]]");
    lines.push(`name = ${formatTomlString(action.name)}`);
    if (action.icon) {
      lines.push(`icon = ${formatTomlString(action.icon)}`);
    }
    lines.push(`command = ${formatTomlString(action.command)}`);
    if (action.platform) {
      lines.push(`platform = ${formatTomlString(action.platform)}`);
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

/**
 * Only persist complete actions; drafts may be partially filled while editing.
 */
function getPersistedActions(
  actions: Array<LocalEnvironmentActionDraft>,
): Array<LocalEnvironmentActionDraft> {
  const persistedActions = new Array<LocalEnvironmentActionDraft>();
  for (const action of actions) {
    const trimmedName = action.name.trim();
    const trimmedCommand = action.command.trim();
    if (trimmedName.length === 0 || trimmedCommand.length === 0) {
      continue;
    }
    persistedActions.push({
      ...action,
      name: trimmedName,
      command: trimmedCommand,
    });
  }
  return persistedActions;
}

function createActionId(): string {
  return crypto.randomUUID();
}

function appendLifecycleSection(
  lines: Array<string>,
  sectionName: "setup" | "cleanup",
  script: string,
  platformScripts: LocalEnvironmentLifecyclePlatformScripts,
): void {
  const platformEntries = getLifecyclePlatformEntries(platformScripts);
  if (
    sectionName === "setup" ||
    script.length > 0 ||
    platformEntries.length > 0
  ) {
    lines.push("");
    lines.push(`[${sectionName}]`);
    lines.push(`script = ${formatTomlString(script)}`);
  }
  if (platformEntries.length === 0) {
    return;
  }
  lines.push("");
  for (const [index, entry] of platformEntries.entries()) {
    lines.push(`[${sectionName}.${entry.platform}]`);
    lines.push(`script = ${formatTomlString(entry.script)}`);
    if (index < platformEntries.length - 1) {
      lines.push("");
    }
  }
}

function getLifecyclePlatformEntries(
  scripts: LocalEnvironmentLifecyclePlatformScripts,
): Array<{ platform: LocalEnvironmentPlatform; script: string }> {
  const entries = new Array<{
    platform: LocalEnvironmentPlatform;
    script: string;
  }>();
  for (const platform of LIFECYCLE_PLATFORM_ORDER) {
    const script = scripts[platform];
    if (!script || script.length === 0) {
      continue;
    }
    entries.push({ platform, script });
  }
  return entries;
}

function formatTomlString(value: string): string {
  const normalized = value.replace(/\r\n/g, "\n");
  if (normalized.includes("\n")) {
    if (!normalized.includes("'''")) {
      return `'''\n${normalized}\n'''`;
    }
    const escaped = normalized.replace(/\\/g, "\\\\").replace(/"""/g, '\\"""');
    return `"""\n${escaped}\n"""`;
  }
  return JSON.stringify(normalized);
}

export function getEnvironmentActionsMode({
  codexWorktree,
  localEnvironments,
  localEnvironmentsLoading,
  resolvedEnvironmentConfigPath,
}: {
  codexWorktree: boolean;
  localEnvironments: Array<{ type: "success" | "error" }>;
  localEnvironmentsLoading: boolean;
  resolvedEnvironmentConfigPath: string | null;
}): "selector" | "setup" | "actions" {
  if (resolvedEnvironmentConfigPath != null) {
    return "actions";
  }
  const hasUsableEnvironment = localEnvironments.some((environment) => {
    return environment.type === "success";
  });
  if (!codexWorktree && (localEnvironmentsLoading || hasUsableEnvironment)) {
    return "selector";
  }
  return "setup";
}
