// Used by above-composer recommended plugin suggestions only.
export const RECOMMENDED_APP_NAMES = new Set([
  "adobe acrobat",
  "adobe photoshop",
  "adobe express",
  "airtable",
  "agentforce sales",
  "canva",
  "cloudinary",
  "clay",
  "datadog",
  "dropbox",
  "figma",
  "github",
  "gmail",
  "google calendar",
  "google docs",
  "google drive",
  "google meet",
  "google sheets",
  "google slides",
  "gitlab issues",
  "heygen",
  "hubspot",
  "hugging face",
  "intercom",
  "intuit turbotax",
  "linear",
  "miro",
  "notion",
  "ramp",
  "slack",
  "slack (openai internal)",
  "resend",
  "statsig",
  "stripe",
  "teams",
  "vercel",
  "zoom",
]);
